# CMSC 197 (Machine Learning) - Quiz 1
### Earl James Q. Rentillo

In [1]:
import numpy as np

# Part 1.

### 1.1 Creating arrays y_hat and y and initializing elements

In [2]:
y_hat = np.linspace(-1, 1, num=20)
y = np.linspace(0, 1, num=20)

print("y_hat: \n" + str(y_hat) + "\n")
print("y: \n" + str(y) + "\n")

y_hat: 
[-1.         -0.89473684 -0.78947368 -0.68421053 -0.57894737 -0.47368421
 -0.36842105 -0.26315789 -0.15789474 -0.05263158  0.05263158  0.15789474
  0.26315789  0.36842105  0.47368421  0.57894737  0.68421053  0.78947368
  0.89473684  1.        ]

y: 
[0.         0.05263158 0.10526316 0.15789474 0.21052632 0.26315789
 0.31578947 0.36842105 0.42105263 0.47368421 0.52631579 0.57894737
 0.63157895 0.68421053 0.73684211 0.78947368 0.84210526 0.89473684
 0.94736842 1.        ]



### 1.2 Calculating shape and dimension

In [3]:
y_hat_shape = y_hat.shape
y_hat_dim = y_hat.ndim

y_shape = y.shape
y_dim = y.ndim

print("shape of array y_hat: " + str(y_hat_shape))
print("dimension of array_hat: " + str(y_hat_dim) + "\n")
print("shape of array y: " + str(y_shape))
print("dimension of array y: " + str(y_dim))

shape of array y_hat: (20,)
dimension of array_hat: 1

shape of array y: (20,)
dimension of array y: 1


### 1.3 Calculating loss values

Mean Squared Error

In [4]:
def mse(y_hat, y):
    N = y_hat.shape[0]
    sum = 0
    for i in range(N):
        sq_diff = (y_hat[i] - y[i]) ** 2
        sum += sq_diff
    L = 1/N * sum
    return("Mean Squared Error: " + str(L))

mse(y_hat,y)

'Mean Squared Error: 0.34210526315789475'

Mean Absolute Error

In [5]:
def mae(y_hat, y):
    n = y_hat.shape[0]
    sum = 0
    for i in range(n):
        abs_diff = abs(y_hat[i] - y[i])
        sum += abs_diff
    L = 1/n * sum
    return("Mean Absolute Error: " + str(L))

mae(y_hat,y)

'Mean Absolute Error: 0.5000000000000001'

Mean Squared Logarithmic Error 

In [6]:
def msle(y_hat, y):
    n = y_hat.shape[0]
    sum = 0
    for i in range(n):
        if (y_hat[i]+1 == 0 and y[i]+1 == 1) or (y_hat[i]+1 == 1 and y[i]+1 == 0):
            L = "Error. Exactly one of the target variables in the same location cannot be 0."
        elif (y_hat[i]+1 < 0) or (y[i]+1 < 0):
            L = "Error. Cannot compute log of negative number."
        else:  
            sq_log = (np.log(y_hat[i] + 1) - np.log(y[i] + 1)) ** 2
            sum += sq_log
    return("Mean Squared Logarithmic Error: " + str(L))

msle(y_hat,y)    

'Mean Squared Logarithmic Error: Error. Exactly one of the target variables in the same location cannot be 0.'

Mean Absolute Percentage Error

In [7]:
def mape(y_hat, y):
    n = y_hat.shape[0]
    sum = 0
    for i in range(n):
        if y[i] == 0:
            L = "Division by zero error. MAPE is infinite."
            break
        abs_div = abs((y_hat[i] - y[i])/y[i])
        sum += abs_div
        L = 1/n
    return("Mean Absolute Percentage Error: " + str(L))

mape(y_hat,y)   

'Mean Absolute Percentage Error: Division by zero error. MAPE is infinite.'

# Part 2.

In [8]:
M = np.arange(1, 17)
print("array M: " + str(M))

array M: [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16]


### 2.1 Reshaping array M

In [9]:
N = M.reshape(4,4)
print("array N: \n" + str(N))

array N: 
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


### 2.2 Getting the 2nd row of N

In [10]:
print("2nd row of N: " + str(N[1]))

2nd row of N: [5 6 7 8]


### 2.3 Getting the minimum values for each column of N

In [11]:
min_array = np.min(N, axis = 0)

for i in range(len(min_array)):
    print("min. value for column " + str(i) + ": " + str(min_array[i]))

min. value for column 0: 1
min. value for column 1: 2
min. value for column 2: 3
min. value for column 3: 4


###  2.4 Getting the locations of the minimum values for each column of N

In [12]:
loc_list=[]
for i in range(len(min_array)):
    loc = [z[0] for z in np.where(N == min_array[i])]
    loc_list.append(loc)

for i in range(len(loc_list)):
    print("location of the min. value for column " + str(i) + ": N" + str(loc_list[i]))

location of the min. value for column 0: N[0, 0]
location of the min. value for column 1: N[0, 1]
location of the min. value for column 2: N[0, 2]
location of the min. value for column 3: N[0, 3]


### 2.5 Getting the average of the whole matrix

In [13]:
sum = 0
for i in N:
    for j in i:
        sum += j
        
average = sum/N.size
print("average of the whole matrix: " + str(average))

average of the whole matrix: 8.5


### 2.6 Creating a vector V with 4 elements, each element is 1

In [14]:
V = np.ones((4,), dtype='int32')
print("vector V: " + str(V))

vector V: [1 1 1 1]


### 2.7 Taking the dot product of N and V

In [15]:
print("dot product of N and V: " + str(np.dot(N, V)))

dot product of N and V: [10 26 42 58]
